apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: test2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: disc99/nginx-test:t1
        ports:
        - containerPort: 80
